// Array de países válidos para el campo de nacionalidad en Cloudbeds
const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Côte d'Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria (Syrian Arab Republic)",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe"
];

// Mapeo de nombres alternativos/traducciones a nombres oficiales
const countryAliases = {
  // Español -> Inglés
  "españa": "Spain",
  "alemania": "Germany",
  "francia": "France",
  "italia": "Italy",
  "reino unido": "United Kingdom",
  "estados unidos": "United States",
  "eeuu": "United States",
  "usa": "United States",
  "paises bajos": "Netherlands",
  "holanda": "Netherlands",
  "belgica": "Belgium",
  "suiza": "Switzerland",
  "austria": "Austria",
  "portugal": "Portugal",
  "grecia": "Greece",
  "irlanda": "Ireland",
  "dinamarca": "Denmark",
  "suecia": "Sweden",
  "noruega": "Norway",
  "finlandia": "Finland",
  "polonia": "Poland",
  "rumania": "Romania",
  "hungria": "Hungary",
  "chequia": "Czech Republic",
  "republica checa": "Czech Republic",
  "eslovaquia": "Slovakia",
  "croacia": "Croatia",
  "eslovenia": "Slovenia",
  "serbia": "Serbia",
  "bulgaria": "Bulgaria",
  "ucrania": "Ukraine",
  "rusia": "Russian Federation",
  "federacion rusa": "Russian Federation",
  "turquia": "Turkey",
  "marruecos": "Morocco",
  "argelia": "Algeria",
  "tunez": "Tunisia",
  "egipto": "Egypt",
  "sudafrica": "South Africa",
  "argentina": "Argentina",
  "brasil": "Brazil",
  "chile": "Chile",
  "colombia": "Colombia",
  "peru": "Peru",
  "mexico": "Mexico",
  "venezuela": "Venezuela",
  "ecuador": "Ecuador",
  "bolivia": "Bolivia",
  "uruguay": "Uruguay",
  "paraguay": "Paraguay",
  "cuba": "Cuba",
  "republica dominicana": "Dominican Republic",
  "china": "China",
  "japon": "Japan",
  "corea": "Korea",
  "corea del sur": "Korea",
  "india": "India",
  "tailandia": "Thailand",
  "vietnam": "Vietnam",
  "filipinas": "Philippines",
  "indonesia": "Indonesia",
  "malasia": "Malaysia",
  "singapur": "Singapore",
  "australia": "Australia",
  "nueva zelanda": "New Zealand",
  "canada": "Canada",
  "emiratos arabes unidos": "United Arab Emirates",
  "arabia saudita": "Saudi Arabia",
  "arabia saudi": "Saudi Arabia",
  "israel": "Israel",
  "libano": "Lebanon",
  "jordania": "Jordan",
  "siria": "Syria (Syrian Arab Republic)",
  "irak": "Iraq",
  "iran": "Iran",
  "afganistan": "Afghanistan",
  "pakistán": "Pakistan",
  "pakistan": "Pakistan",
  // Gentilicios comunes
  "spanish": "Spain",
  "german": "Germany",
  "french": "France",
  "italian": "Italy",
  "british": "United Kingdom",
  "american": "United States",
  "dutch": "Netherlands",
  "belgian": "Belgium",
  "swiss": "Switzerland",
  "austrian": "Austria",
  "portuguese": "Portugal",
  "greek": "Greece",
  "irish": "Ireland",
  "danish": "Denmark",
  "swedish": "Sweden",
  "norwegian": "Norway",
  "finnish": "Finland",
  "polish": "Poland",
  "romanian": "Romania",
  "hungarian": "Hungary",
  "czech": "Czech Republic",
  "slovak": "Slovakia",
  "croatian": "Croatia",
  "slovenian": "Slovenia",
  "serbian": "Serbia",
  "bulgarian": "Bulgaria",
  "ukrainian": "Ukraine",
  "russian": "Russian Federation",
  "turkish": "Turkey",
  "moroccan": "Morocco",
  "algerian": "Algeria",
  "tunisian": "Tunisia",
  "egyptian": "Egypt",
  "south african": "South Africa",
  "argentine": "Argentina",
  "argentinian": "Argentina",
  "brazilian": "Brazil",
  "chilean": "Chile",
  "colombian": "Colombia",
  "peruvian": "Peru",
  "mexican": "Mexico",
  "venezuelan": "Venezuela",
  "ecuadorian": "Ecuador",
  "bolivian": "Bolivia",
  "uruguayan": "Uruguay",
  "paraguayan": "Paraguay",
  "cuban": "Cuba",
  "dominican": "Dominican Republic",
  "chinese": "China",
  "japanese": "Japan",
  "korean": "Korea",
  "indian": "India",
  "thai": "Thailand",
  "vietnamese": "Vietnam",
  "filipino": "Philippines",
  "indonesian": "Indonesia",
  "malaysian": "Malaysia",
  "singaporean": "Singapore",
  "australian": "Australia",
  "new zealander": "New Zealand",
  "canadian": "Canada"
};
